language: node_js
services: mongodb
node_js:
  - "0.10"
notifications:
  email: false
before_script:
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g supertest
  - node server.js
script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
